### PR TITLE
[REVIEWING] Release/0.7.2

### PR DESCRIPTION
**Pull request by JaminB**
- Zeek 3.0.3 support
- Adds dynamited service and component
- Enhancements to service modules; base service modules introduced.
- Enhancements to systemd integration
   - stdout/stderr passthrough
   - exit status
   - running status
- Commandline statuses now pretty-print by default

### CODE REVIEW

**Comment by JaminB** [comment]
- Adds managerd service and component
- Enhancements to service modules; inheritance.
- Zeek 3.0.3 support
- Commandline statuses now pretty-print by default

**Comment by pmphry** [comment]
Attempted installation from the release/0.7.2 branch on CENTOS 7.8.2003 failed with fatal error.  Most recent output from dynamite cli follows:

```
2020-08-10 09:25:56 AGENT_CMP       INFO       | *** Agent installed successfully. ***
2020-08-10 09:25:56 AGENT_CMP       INFO       | Next, Start your agent: 'dynamite agent start'.
[ap@agent3 dynamite-nsm]$ sudo dynamite agent status
[sudo] password for ap:
2020-08-10 09:27:37 DYNAMITE_CMD    INFO       | LOG LEVEL: 20
2020-08-10 09:27:37 DYNAMITE_CMD    INFO       | LOG FILE: /var/log/dynamite/dynamite-10-08-2020.log
2020-08-10 09:27:37 DYNAMITE_CMD    CRITICAL   | Fatal error. Add --verbose flag for details. Exiting.
[ap@agent3 dynamite-nsm]$ sudo dynamite agent status --verbose
2020-08-10 09:27:43 DYNAMITE_CMD    INFO       | LOG LEVEL: 10
2020-08-10 09:27:43 DYNAMITE_CMD    INFO       | LOG FILE: /var/log/dynamite/dynamite-10-08-2020.log
2020-08-10 09:27:44 DYNAMITE_CMD    CRITICAL   | Fatal error. Exiting.
2020-08-10 09:27:44 DYNAMITE_CMD    DEBUG      | Fatal error. Exiting; "getpwnam(): name not found: 'dynamite'"
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/EGG-INFO/scripts/dynamite", line 90, in <module>
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/agent/component.py", line 138, in __init__
    self.execute_process_status_strategy()
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/base/component.py", line 63, in execute_strategy_function
    self.execute_strategy(self.component_name, strategy)
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/base/component.py", line 82, in execute_strategy
    strategy.execute_strategy()
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/base/execution_strategy.py", line 59, in execute_strategy
    print_text_message(func(**args))
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/agent/execution_strategy.py", line 53, in get_agent_status
    pretty_print_status=pretty_print_status).status()
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/services/suricata/process.py", line 20, in __init__
    verbose=verbose, pretty_print_status=pretty_print_status)
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/services/base/process.py", line 31, in __init__
    self.pid = self._get_pid(pid_file)
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/services/base/process.py", line 39, in _get_pid
    utilities.set_ownership_of_file(h)
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/utilities.py", line 542, in set_ownership_of_file
    uid = pwd.getpwnam(user).pw_uid
KeyError: "getpwnam(): name not found: 'dynamite'"
```

I checked /etc/passwd and the dynamite user is not there.  I then tried the utilities.create_dynamite_user method directly from an interactive shell and it worked fine.  After looking at at the AgentInstallationStrategy class it appears the create user method is not being called.

**Comment by pmphry** [comment]
Systemd is on CENTOS is complaining about a few things.  This one is pointing out we aren't properly setting permissions on the service unit files.  

```
Aug 10 13:32:22 agent3 systemd: Configuration file /etc/systemd/system/filebeat.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Aug 10 13:32:22 agent3 systemd: Configuration file /etc/systemd/system/filebeat.service is marked world-writable. Please remove world writability permission bits. Proceeding anyway.
Aug 10 13:32:22 agent3 systemd: Configuration file /etc/systemd/system/zeek.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Aug 10 13:32:22 agent3 systemd: Configuration file /etc/systemd/system/zeek.service is marked world-writable. Please remove world writability permission bits. Proceeding anyway.
Aug 10 13:32:22 agent3 systemd: Configuration file /etc/systemd/system/dynamite-agent.target is marked executable. Please remove executable permission bits. Proceeding anyway.
Aug 10 13:32:22 agent3 systemd: Configuration file /etc/systemd/system/dynamite-agent.target is marked world-writable. Please remove world writability permission bits. Proceeding anyway.
Aug 10 13:32:22 agent3 systemd: Configuration file /etc/systemd/system/suricata.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Aug 10 13:32:22 agent3 systemd: Configuration file /etc/systemd/system/suricata.service is marked world-writable. Please remove world writability permission bits. Proceeding anyway.
```

**Comment by pmphry** [comment]
Systemd also doesn't like our `PYTHON_BIN` declaration in the zeek unit file.  Can we set this dynamically at install time?

```
Aug 10 13:32:22 agent3 systemd: [/etc/systemd/system/zeek.service:9] Invalid environment assignment, ignoring: "PYTHON_BIN=`whereis python | tr ' ' '\n' | grep -v config | grep -v 3 | cut -d$'\n' -f2`"
```

**Comment by pmphry** [comment]
Also looks like the CommunityID plugin didn't get installed.  Zeek won't start because of it. 

```
Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
```

Looking to see if the installation got interrupted or something.

**Comment by pmphry** [comment]
> Systemd also doesn't like our `PYTHON_BIN` declaration in the zeek unit file. Can we set this dynamically at install time?
> 
> ```
> Aug 10 13:32:22 agent3 systemd: [/etc/systemd/system/zeek.service:9] Invalid environment assignment, ignoring: "PYTHON_BIN=`whereis python | tr ' ' '\n' | grep -v config | grep -v 3 | cut -d$'\n' -f2`"
> ```

Now seeing this is finding and setting the location of the python2.7 environment.  Clearly a relic from the old days.  

```
[ap@agent3 dynamite]$ whereis python | tr ' ' '\n' | grep -v config | grep -v 3 | cut -d$'\n' -f2
python:
/usr/bin/python
/usr/bin/python2.7
/usr/lib/python2.7
/usr/lib64/python2.7
/etc/python
/usr/include/python2.7
/usr/share/man/man1/python.1.gz
```

**Comment by pmphry** [comment]
> Also looks like the CommunityID plugin didn't get installed. Zeek won't start because of it.
> 
> ```
> Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> ```
> 
> Looking to see if the installation got interrupted or something.

None of the Zeek plugins made it, commented out the community_id load statement in local.zeek, and its now saying it can't find the AF_PACKET plugin. 

```
[ap@agent3 dynamite]$ sudo zeekctl deploy
checking configurations ...
dynamite-logger scripts failed.
fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts

dynamite-manager scripts failed.
fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts

dynamite-proxy-1 scripts failed.
fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts

dynamite-worker-ens224-1 scripts failed.
fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
```

**Comment by pmphry** [comment]
> > Also looks like the CommunityID plugin didn't get installed. Zeek won't start because of it.
> > ```
> > Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> > Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> > Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> > Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> > ```
> > 
> > 
> > Looking to see if the installation got interrupted or something.
> 
> None of the Zeek plugins made it, commented out the community_id load statement in local.zeek, and its now saying it can't find the AF_PACKET plugin.
> 
> ```
> [ap@agent3 dynamite]$ sudo zeekctl deploy
> checking configurations ...
> dynamite-logger scripts failed.
> fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
> 
> dynamite-manager scripts failed.
> fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
> 
> dynamite-proxy-1 scripts failed.
> fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
> 
> dynamite-worker-ens224-1 scripts failed.
> fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
> ```

I uninstalled, then reran the agent install.  Looks like it's failing after it tried to configure the AF_PACKET plugin.  When I retry the agent install with the `--verbose` flag, it sees that zeek is installed and continues on like normal.  The missing Zeek plugins never get caught.  

```
2020-08-10 15:05:38,828 |            ZEEK |              install |                                    setup_zeek |  537 |     INFO |  Creating Zeek installation, configuration and logging directories.
2020-08-10 15:05:38,829 |            ZEEK |              install |                                    setup_zeek |  547 |     INFO |  Compiling Zeek from source. This can take up to 30 minutes.
2020-08-10 15:05:39,831 |            ZEEK |              install |                                    setup_zeek |  551 |     INFO |  Configuring Zeek.
2020-08-10 15:05:52,191 |            ZEEK |              install |                                    setup_zeek |  574 |     INFO |  Compiling Zeek.
2020-08-10 15:06:25,002 |            ZEEK |              install |                                    setup_zeek |  607 |     INFO |  Updating Zeek default home path [/opt/dynamite/zeek]
2020-08-10 15:06:25,007 |            ZEEK |              install |                                    setup_zeek |  611 |     INFO |  Updating Zeek default script path [/etc/dynamite/zeek/]
2020-08-10 15:06:25,012 |            ZEEK |              install |                                    setup_zeek |  624 |     INFO |  Overwriting Zeek node.cfg file with our changes.
2020-08-10 15:06:25,018 |            ZEEK |              install |                              get_zeek_workers |  102 |     INFO |  Calculating optimal Zeek worker strategy [strategy: aggressive].
2020-08-10 15:06:25,018 |            ZEEK |              install |                              get_zeek_workers |  164 |     INFO |  Zeek Worker Count: 1
2020-08-10 15:06:25,071 |            ZEEK |              install |                                    setup_zeek |  664 |     INFO |  Installing Zeek systemd service.
2020-08-10 15:06:25,229 |            ZEEK |              install |                   setup_dynamite_zeek_scripts |  361 |     INFO |  Setting up Zeek scripts.
2020-08-10 15:06:25,229 |            ZEEK |              install |                   setup_dynamite_zeek_scripts |  376 |     INFO |  Installing third-party Zeek scripts.
2020-08-10 15:06:25,239 |            ZEEK |              install |                   setup_zeek_af_packet_plugin |  227 |     INFO |  Configuring Zeek Zeek_AF_Packet plugin.
2020-08-10 15:06:25,275 |    DYNAMITE_CMD |             dynamite |                                      <module> |  110 | CRITICAL |  Fatal error. Add --verbose flag for details. Exiting.
2020-08-10 15:54:43,582 |    DYNAMITE_CMD |             dynamite |                                      <module> |   71 |     INFO |  LOG LEVEL: 10
2020-08-10 15:54:43,582 |    DYNAMITE_CMD |             dynamite |                                      <module> |   72 |     INFO |  LOG FILE: /var/log/dynamite/dynamite-10-08-2020.log
2020-08-10 15:54:43,588 |       AGENT_CMP |   execution_strategy |                                   log_message |   32 |     INFO |  Skipping Filebeat installation; already installed
2020-08-10 15:54:43,589 |       AGENT_CMP |   execution_strategy |                                   log_message |   32 |     INFO |  Skipping Zeek installation.
```

**Comment by pmphry** [comment]
> > > Also looks like the CommunityID plugin didn't get installed. Zeek won't start because of it.
> > > ```
> > > Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> > > Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> > > Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> > > Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> > > ```
> > > 
> > > 
> > > Looking to see if the installation got interrupted or something.
> > 
> > 
> > None of the Zeek plugins made it, commented out the community_id load statement in local.zeek, and its now saying it can't find the AF_PACKET plugin.
> > ```
> > [ap@agent3 dynamite]$ sudo zeekctl deploy
> > checking configurations ...
> > dynamite-logger scripts failed.
> > fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
> > 
> > dynamite-manager scripts failed.
> > fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
> > 
> > dynamite-proxy-1 scripts failed.
> > fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
> > 
> > dynamite-worker-ens224-1 scripts failed.
> > fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
> > ```
> 
> I uninstalled, then reran the agent install. Looks like it's failing after it tried to configure the AF_PACKET plugin. When I retry the agent install with the `--verbose` flag, it sees that zeek is installed and continues on like normal. The missing Zeek plugins never get caught.
> 
> ```
> 2020-08-10 15:05:38,828 |            ZEEK |              install |                                    setup_zeek |  537 |     INFO |  Creating Zeek installation, configuration and logging directories.
> 2020-08-10 15:05:38,829 |            ZEEK |              install |                                    setup_zeek |  547 |     INFO |  Compiling Zeek from source. This can take up to 30 minutes.
> 2020-08-10 15:05:39,831 |            ZEEK |              install |                                    setup_zeek |  551 |     INFO |  Configuring Zeek.
> 2020-08-10 15:05:52,191 |            ZEEK |              install |                                    setup_zeek |  574 |     INFO |  Compiling Zeek.
> 2020-08-10 15:06:25,002 |            ZEEK |              install |                                    setup_zeek |  607 |     INFO |  Updating Zeek default home path [/opt/dynamite/zeek]
> 2020-08-10 15:06:25,007 |            ZEEK |              install |                                    setup_zeek |  611 |     INFO |  Updating Zeek default script path [/etc/dynamite/zeek/]
> 2020-08-10 15:06:25,012 |            ZEEK |              install |                                    setup_zeek |  624 |     INFO |  Overwriting Zeek node.cfg file with our changes.
> 2020-08-10 15:06:25,018 |            ZEEK |              install |                              get_zeek_workers |  102 |     INFO |  Calculating optimal Zeek worker strategy [strategy: aggressive].
> 2020-08-10 15:06:25,018 |            ZEEK |              install |                              get_zeek_workers |  164 |     INFO |  Zeek Worker Count: 1
> 2020-08-10 15:06:25,071 |            ZEEK |              install |                                    setup_zeek |  664 |     INFO |  Installing Zeek systemd service.
> 2020-08-10 15:06:25,229 |            ZEEK |              install |                   setup_dynamite_zeek_scripts |  361 |     INFO |  Setting up Zeek scripts.
> 2020-08-10 15:06:25,229 |            ZEEK |              install |                   setup_dynamite_zeek_scripts |  376 |     INFO |  Installing third-party Zeek scripts.
> 2020-08-10 15:06:25,239 |            ZEEK |              install |                   setup_zeek_af_packet_plugin |  227 |     INFO |  Configuring Zeek Zeek_AF_Packet plugin.
> 2020-08-10 15:06:25,275 |    DYNAMITE_CMD |             dynamite |                                      <module> |  110 | CRITICAL |  Fatal error. Add --verbose flag for details. Exiting.
> 2020-08-10 15:54:43,582 |    DYNAMITE_CMD |             dynamite |                                      <module> |   71 |     INFO |  LOG LEVEL: 10
> 2020-08-10 15:54:43,582 |    DYNAMITE_CMD |             dynamite |                                      <module> |   72 |     INFO |  LOG FILE: /var/log/dynamite/dynamite-10-08-2020.log
> 2020-08-10 15:54:43,588 |       AGENT_CMP |   execution_strategy |                                   log_message |   32 |     INFO |  Skipping Filebeat installation; already installed
> 2020-08-10 15:54:43,589 |       AGENT_CMP |   execution_strategy |                                   log_message |   32 |     INFO |  Skipping Zeek installation.
> ```

Ok I see... CMake 3.0 or higher is required for the AF_PACKET plugin.  Installed the `cmake3` package via yum and Zeek install proceeded without issue. 

```
2020-08-10 16:56:58 ZEEK            INFO       | Configuring Zeek Zeek_AF_Packet plugin.
./configure --zeek-dist=/tmp/dynamite/install_cache/zeek-3.0.3 --install-root=/etc/dynamite/zeek/ --with-latest-kernel
Build Directory        : build
Zeek Source Directory   : /tmp/dynamite/install_cache/zeek-3.0.3
CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
  CMake 3.0 or higher is required.  You are running version 2.8.12.2

-- Configuring incomplete, errors occurred!
2020-08-10 16:56:58 ZEEK            DEBUG      | Zeek_AF_Packet configuration returned non-zero; exit-code: 1
2020-08-10 16:56:58 DYNAMITE_CMD    CRITICAL   | Fatal error. Exiting.
2020-08-10 16:56:58 DYNAMITE_CMD    DEBUG      | Fatal error. Exiting; An error occurred while attempting to install component: An error occurred while installing Zeek: Zeek_AF_Packet configuration returned non-zero; exit-code: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/EGG-INFO/scripts/dynamite", line 90, in <module>
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/agent/component.py", line 94, in __init__
    self.execute_install_strategy()
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/base/component.py", line 63, in execute_strategy_function
    self.execute_strategy(self.component_name, strategy)
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/base/component.py", line 82, in execute_strategy
    strategy.execute_strategy()
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/base/execution_strategy.py", line 55, in execute_strategy
    func(**args)
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/services/zeek/install.py", line 694, in install_zeek
    zeek_installer.setup_dynamite_zeek_scripts()
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/services/zeek/install.py", line 412, in setup_dynamite_zeek_scripts
    self.setup_zeek_af_packet_plugin()
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/services/zeek/install.py", line 253, in setup_zeek_af_packet_plugin
    config_zeek_af_packet_process.returncode))
dynamite_nsm.services.zeek.exceptions.InstallZeekError: An error occurred while attempting to install component: An error occurred while installing Zeek: Zeek_AF_Packet configuration returned non-zero; exit-code: 1
```

**Comment by pmphry** [comment]
> > > > Also looks like the CommunityID plugin didn't get installed. Zeek won't start because of it.
> > > > ```
> > > > Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> > > > Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> > > > Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> > > > Aug 10 14:03:57 agent3 bash: fatal error in /etc/dynamite/zeek/site/local.zeek, line 54: can't find Corelight/CommunityID
> > > > ```
> > > > 
> > > > 
> > > > Looking to see if the installation got interrupted or something.
> > > 
> > > 
> > > None of the Zeek plugins made it, commented out the community_id load statement in local.zeek, and its now saying it can't find the AF_PACKET plugin.
> > > ```
> > > [ap@agent3 dynamite]$ sudo zeekctl deploy
> > > checking configurations ...
> > > dynamite-logger scripts failed.
> > > fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
> > > 
> > > dynamite-manager scripts failed.
> > > fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
> > > 
> > > dynamite-proxy-1 scripts failed.
> > > fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
> > > 
> > > dynamite-worker-ens224-1 scripts failed.
> > > fatal error in /etc/dynamite/zeek/site/local.zeek, line 55: can't find Zeek_AF_Packet/scripts
> > > ```
> > 
> > 
> > I uninstalled, then reran the agent install. Looks like it's failing after it tried to configure the AF_PACKET plugin. When I retry the agent install with the `--verbose` flag, it sees that zeek is installed and continues on like normal. The missing Zeek plugins never get caught.
> > ```
> > 2020-08-10 15:05:38,828 |            ZEEK |              install |                                    setup_zeek |  537 |     INFO |  Creating Zeek installation, configuration and logging directories.
> > 2020-08-10 15:05:38,829 |            ZEEK |              install |                                    setup_zeek |  547 |     INFO |  Compiling Zeek from source. This can take up to 30 minutes.
> > 2020-08-10 15:05:39,831 |            ZEEK |              install |                                    setup_zeek |  551 |     INFO |  Configuring Zeek.
> > 2020-08-10 15:05:52,191 |            ZEEK |              install |                                    setup_zeek |  574 |     INFO |  Compiling Zeek.
> > 2020-08-10 15:06:25,002 |            ZEEK |              install |                                    setup_zeek |  607 |     INFO |  Updating Zeek default home path [/opt/dynamite/zeek]
> > 2020-08-10 15:06:25,007 |            ZEEK |              install |                                    setup_zeek |  611 |     INFO |  Updating Zeek default script path [/etc/dynamite/zeek/]
> > 2020-08-10 15:06:25,012 |            ZEEK |              install |                                    setup_zeek |  624 |     INFO |  Overwriting Zeek node.cfg file with our changes.
> > 2020-08-10 15:06:25,018 |            ZEEK |              install |                              get_zeek_workers |  102 |     INFO |  Calculating optimal Zeek worker strategy [strategy: aggressive].
> > 2020-08-10 15:06:25,018 |            ZEEK |              install |                              get_zeek_workers |  164 |     INFO |  Zeek Worker Count: 1
> > 2020-08-10 15:06:25,071 |            ZEEK |              install |                                    setup_zeek |  664 |     INFO |  Installing Zeek systemd service.
> > 2020-08-10 15:06:25,229 |            ZEEK |              install |                   setup_dynamite_zeek_scripts |  361 |     INFO |  Setting up Zeek scripts.
> > 2020-08-10 15:06:25,229 |            ZEEK |              install |                   setup_dynamite_zeek_scripts |  376 |     INFO |  Installing third-party Zeek scripts.
> > 2020-08-10 15:06:25,239 |            ZEEK |              install |                   setup_zeek_af_packet_plugin |  227 |     INFO |  Configuring Zeek Zeek_AF_Packet plugin.
> > 2020-08-10 15:06:25,275 |    DYNAMITE_CMD |             dynamite |                                      <module> |  110 | CRITICAL |  Fatal error. Add --verbose flag for details. Exiting.
> > 2020-08-10 15:54:43,582 |    DYNAMITE_CMD |             dynamite |                                      <module> |   71 |     INFO |  LOG LEVEL: 10
> > 2020-08-10 15:54:43,582 |    DYNAMITE_CMD |             dynamite |                                      <module> |   72 |     INFO |  LOG FILE: /var/log/dynamite/dynamite-10-08-2020.log
> > 2020-08-10 15:54:43,588 |       AGENT_CMP |   execution_strategy |                                   log_message |   32 |     INFO |  Skipping Filebeat installation; already installed
> > 2020-08-10 15:54:43,589 |       AGENT_CMP |   execution_strategy |                                   log_message |   32 |     INFO |  Skipping Zeek installation.
> > ```
> 
> Ok I see... CMake 3.0 or higher is required for the AF_PACKET plugin. Installed the `cmake3` package via yum and Zeek install proceeded without issue.
> 
> ```
> 2020-08-10 16:56:58 ZEEK            INFO       | Configuring Zeek Zeek_AF_Packet plugin.
> ./configure --zeek-dist=/tmp/dynamite/install_cache/zeek-3.0.3 --install-root=/etc/dynamite/zeek/ --with-latest-kernel
> Build Directory        : build
> Zeek Source Directory   : /tmp/dynamite/install_cache/zeek-3.0.3
> CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
>   CMake 3.0 or higher is required.  You are running version 2.8.12.2
> 
> -- Configuring incomplete, errors occurred!
> 2020-08-10 16:56:58 ZEEK            DEBUG      | Zeek_AF_Packet configuration returned non-zero; exit-code: 1
> 2020-08-10 16:56:58 DYNAMITE_CMD    CRITICAL   | Fatal error. Exiting.
> 2020-08-10 16:56:58 DYNAMITE_CMD    DEBUG      | Fatal error. Exiting; An error occurred while attempting to install component: An error occurred while installing Zeek: Zeek_AF_Packet configuration returned non-zero; exit-code: 1
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/EGG-INFO/scripts/dynamite", line 90, in <module>
>   File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/agent/component.py", line 94, in __init__
>     self.execute_install_strategy()
>   File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/base/component.py", line 63, in execute_strategy_function
>     self.execute_strategy(self.component_name, strategy)
>   File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/base/component.py", line 82, in execute_strategy
>     strategy.execute_strategy()
>   File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/components/base/execution_strategy.py", line 55, in execute_strategy
>     func(**args)
>   File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/services/zeek/install.py", line 694, in install_zeek
>     zeek_installer.setup_dynamite_zeek_scripts()
>   File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/services/zeek/install.py", line 412, in setup_dynamite_zeek_scripts
>     self.setup_zeek_af_packet_plugin()
>   File "/usr/local/lib/python3.6/site-packages/dynamite_nsm-0.7.1-py3.6.egg/dynamite_nsm/services/zeek/install.py", line 253, in setup_zeek_af_packet_plugin
>     config_zeek_af_packet_process.returncode))
> dynamite_nsm.services.zeek.exceptions.InstallZeekError: An error occurred while attempting to install component: An error occurred while installing Zeek: Zeek_AF_Packet configuration returned non-zero; exit-code: 1
> ```

Confirmed!  Installing the cmake3 package fixed the dependency and Zeek installed with no issue.

**Pull request merged**
